spring:
  application:
    name: sun-user
  datasource:
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    database: 1

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

mybatis:
  type-aliases-package: com.otsira.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      otsira:
        mapper: debug
        service: info
        controller: info

auth:
  sun:
    jwt:
      user-secret-key: yiixhanyiik@163.com
      user-ttl: 7200000
      user-token-name: authorization

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: CLASS_PATH
    access-key-secret: CLASS_PATH
    bucket-name: ostsiraoss
    region: cn-beijing
    file-dir: dishImages/
    url-prefix: https://ostsiraoss.oss-cn-beijing.aliyuncs.com/

sun:
  wechat:
    appid: wx2b4e26137fabf177
    secret: c7224502dc78a3919da933400d0f951c
    mchid: xxxxxxxxx
    mch-serial-no: xxxxxxxxx
    private-key-file-path: xxxxxxxxx
    api-v3-key: xxxxxxxxx
    we-chat-pay-cert-file-path: xxxxxxxxx
    notify-url: http://www.otsira.org/api/user/notify/paySuccess
    refund-notify-url: http://www.otsira.org/api/user/notify/refundSuccess