spring:
  application:
    name: sun-admin
  datasource:
    url: jdbc:mysql:///sky_take_out
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

server:
  port: 8081
eureka:
  client:
    service-url:
        defaultZone: http://localhost:10086/eureka

mybatis:
  type-aliases-package: com.otsira.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      otsira:
        mapper: debug
        service: info
        controller: info

auth:
  sun:
    jwt:
      admin-secret-key: yiixhanyiik@gmail.com
      admin-ttl: 7200000
      admin-token-name: token_admin
      user-secret-key: yiixhanyiik@163.com
      user-ttl: 7200000
      user-token-name: token_user
    path:
      exclude-paths:
        - /admin/employee/login
        - /user/login

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: CLASS_PATH
    access-key-secret: CLASS_PATH
    bucket-name: ostsiraoss
    region: cn-beijing
    file-dir: dishImages/
    url-prefix: https://ostsiraoss.oss-cn-beijing.aliyuncs.com/
